// <auto-generated />
namespace AutoShopAspNet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migracija2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracija2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806111351365_migracija2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
